version: '2.2'
services:
  test:
    build: .
    command: sh -c ./entrypoint.sh
    volumes:
      - .:/usr/app/
    depends_on:
      - chromedriver
    ports:
      - "3000:3000"
  chromedriver:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=true
      - EXPOSE_X11=true
    ports:
      - 5900:5900
      
